# Generated by Django 4.2.3 on 2025-07-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_remove_course_instructors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_enrollment',
            field=models.IntegerField(default=0),
        ),
    ]
